from typing import Dict,List, TypedDict, Any

class GraphState(TypedDict):
    repo_name: str
    pr_number: int
    head_sha: str               # NEW: We need the commit SHA to get the right file version
    diff_content: str           # The raw code changes
    diff_summary: str           # Summary of what changed (generated by LLM)
    relevant_adrs: List[str]    # Content of retrieved ADRs
    file_content_cache: Dict[str, str] # NEW: Stores filename -> full content
    conversation_history: List[Dict[str, str]] # NEW: Store the chat history here
    initial_critique: str       # The harsh review from the first agent
    final_comment: str          # The polished comment from the second agent